### ISSUE TITLE
No program exit with mouse

### ISSUE THREAD

**Issue by rudi48** [XBMC-Addons/script.xbmc.audio.mixer#1]
Hello,
I am using xbmc.audio.mixer under kodi version 14.
Up to now I did not found a way to exit the mixer window with a mouse action.
When I hit the ESC button on the keyboard, the program will exit.

It would be nice to provide also a program exit via mouse click.

Thank you for the program.
Regards, Rudolf

**Comment by ronie** [comment]
i've added an 'ok' button for mouse users: https://github.com/XBMC-Addons/script.xbmc.audio.mixer/commit/cd66ec1d40ee77f35b96eaf9d1b39f1e4a312eba
