### ISSUE TITLE
Version 3.0, script error in raspbmc

### ISSUE THREAD

**Issue by rudi48** [XBMC-Addons/script.xbmc.audio.mixer#2]
Hello ronie.
Thank you very much for the quick fix.
Unfortunately I will get a "Script Error" when I click on "Start" in "Kodi Audio Mixer" version 3.0, and the program will not start
Regards, Rudolf

**Comment by ronie** [comment]
thanx! strange that it slipped through without me noticing it.

fixed in: https://github.com/XBMC-Addons/script.xbmc.audio.mixer/commit/6bccbc820a7ebf8491fdec7ac13699fca1321d82
